complete -c paw -x                            -a "(__fish_complete_subcommand)"
complete -c paw -r -s c -l config                                                                    -d "path to configuration file (XDG_CONFIG_HOME/paw/paw.ini)"
complete -c paw    -s C -l check-config                                                              -d "verify configuration and exit with 0 if ok, otherwise exit with 1"
complete -c paw -x -s o -l override                                                                  -d "configuration option to override, in form SECTION.KEY=VALUE"
complete -c paw -x -s f -l font               -a "(fc-list : family | sed 's/,/\n/g' | sort | uniq)" -d "font name and style in fontconfig format (monospace)"
complete -c paw -x -s t -l term               -a '(find /usr/share/terminfo -type f -printf "%f\n")' -d "value to set the environment variable TERM to (paw)"
complete -c paw -x -s T -l title                                                                     -d "initial window title"
complete -c paw -x -s a -l app-id                                                                    -d "value to set the app-id property on the Wayland window to (paw)"
complete -c paw -x      -l toplevel-tag                                                              -d "value to set the toplevel-tag property on the Wayland window to"
complete -c paw    -s m -l maximized                                                                 -d "start in maximized mode"
complete -c paw    -s F -l fullscreen                                                                -d "start in fullscreen mode"
complete -c paw    -s L -l login-shell                                                               -d "start shell as a login shell"
complete -c paw -F -s D -l working-directory                                                         -d "initial working directory for the client application (CWD)"
complete -c paw -x -s w -l window-size-pixels                                                        -d "window WIDTHxHEIGHT, in pixels (700x500)"
complete -c paw -x -s W -l window-size-chars                                                         -d "window WIDTHxHEIGHT, in characters (not set)"
complete -c paw -F -s s -l server                                                                    -d "run as server; open terminals by running pawclient"
complete -c paw    -s H -l hold                                                                      -d "remain open after child process exits"
complete -c paw -r -s p -l print-pid                                                                 -d "print PID to this file or FD when up and running (server mode only)"
complete -c paw -x -s d -l log-level           -a "info warning error none"                          -d "log-level (warning)"
complete -c paw -x -s l -l log-colorize        -a "always never auto"                                -d "enable or disable colorization of log output on stderr"
complete -c paw    -s S -l log-no-syslog                                                             -d "disable syslog logging (server mode only)"
complete -c paw -r      -l pty                                                                       -d "display an existing pty instead of creating one"
complete -c paw    -s v -l version                                                                   -d "show the version number and quit"
complete -c paw    -s h -l help                                                                      -d "show help message and quit"
